---
title: Open Source Musings & Snow Time
bibliography: _bibliography/papers.bib
---

Welcome! Here's where I write thoughts on various open source Large Language
Model projects and random things I'm doing.  I'm a former Staff Software
Engineer from Google Translate and until I make it back the states, I'm
spending some time exploring the world of smaller teams and companies.  I
sometimes take on contractor work related to LLMs.  During winter, I spend a
lot of time skiing in Hakuba Japan (if you find yourself there, say hello and I
can show you
around).

## Upcoming Reviews

* [ ] Making KT-Villa with FastChat, LLaVa & RedwoodJS:
  * [ ] A basic overview
  * [ ] Gluing Stable Diffusion and Llava together
  * [ ] Piping in Zephyr-7b
  * [ ] Why the rest of the project was still hard
* [ ] Evaluate some interesting projects:
  * [ ] [ModelFusion](https://modelfusion.dev/guide/)
  * [ ] [llama-cpp-python](https://github.com/abetlen/llama-cpp-python)
  * [ ] [xorbitsai/inference](https://github.com/xorbitsai/inference)
  * [ ] [Lilac](https://lilacml.com/)
* [ ] Try out some more models:
  * [ ] [teknium/OpenHermes-2.5-Mistral-7B](https://huggingface.co/teknium/OpenHermes-2.5-Mistral-7B)
  * [ ] [teknium/Mistral-Trismegistus-7B](https://huggingface.co/teknium/Mistral-Trismegistus-7B)
  * [ ] [liuhaotian/llava-v1.5-7b](https://huggingface.co/liuhaotian/llava-v1.5-7b)
## Selected Publications

---
nocite: |
  @köpf2023openassistant
  @guo-etal-2019-hierarchical
  @45610
  @jurgens-stevens-2010-space
---
